Soieu payment main
NewDeal-MarkeThing/MarkeThing pull request #21
Opened 2024-07-08 10:37 UTC by soieu

## 코드 변경사항

#### AS-IS
- paymentCancelDetail, payment, marketPurchaseRequest의 연관관계가 잘못되어있었습니다.

#### TO-BE
- paymentCancelDetail, payment, marketPurchaseRequest의 연관관계를 다대일에서 일대일로 수정합니다.
- 수수료 결제 기능 추가합니다.

## 테스트 여부
- [ O ] 테스트 코드
- [ O ] API 테스트

2024-07-08 10:47 UTC, sangeun-b approved these changes

2024-07-08 10:47 UTC, sangeun-b commented on src/main/java/com/example/demo/payment/dto/RequestPayDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@JsonNaming를 사용하는 이유는 뭔가용?😮

2024-07-08 10:47 UTC, sangeun-b commented on src/main/java/com/example/demo/payment/service/PaymentService.java
> +    // IamportResponse<Payment> cancelPayment(String paymentId, CancelPaymentRequest request);
필요한 주석일까요?? 😮

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 requested changes
수고하셨습니다~ 리뷰 확인 부탁드려요!

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/marketpurchaserequest/repository/MarketPurchaseRequestRepository.java
>  public interface MarketPurchaseRequestRepository extends JpaRepository<MarketPurchaseRequest,Long> {
, 뒤에 한 칸 띄워주세요~

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/marketpurchaserequest/repository/MarketPurchaseRequestRepository.java
> +    Optional<MarketPurchaseRequest> findRequestAndPaymentAndMember(String id);
JPA 네이밍이 잘못된 것 같아요~ 공부 후 수정 부탁드려요!

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/controller/api/PaymentApiController.java
> +        log.info("결제 응답={}", response.getResponse().toString());
log를 달면 어떤 값이 나오나요?

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/controller/view/PaymentController.java
> +        return "success-payment";
스네이크 표기법으로 고쳐주세요!

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/controller/view/PaymentController.java
> +        return "fail-payment";
스네이크 표기법으로 고쳐주세요!

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/dto/RequestPayDto.java
> +@Data
@Data 어노테이션을 쓰는 것은 필요없는 어노테이션까지 합쳐지기 때문에 지양하는 것이 좋다고 들었습니다! 필요한 어노테이션만 추가해주세요~

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/dto/RequestPayDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
이 어노테이션을 사용하는 이유는 무엇인가요?

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +                .orElseThrow(() -> new IllegalArgumentException("주문이 없습니다."));
에러 응답 형식 지켜주세요~

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +                marketPurchaseRequestRepository.delete(marketPurchaseRequest);
결제 완료가 아니어도 주문을 삭제하는 건 아닌 것 같아요.

2024-07-08 11:06 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +                marketPurchaseRequestRepository.delete(marketPurchaseRequest);
여기서도 구매글 자체를 삭제하는 건 아닌 것 같아요.

2024-07-09 01:41 UTC, soieu commented on src/main/java/com/example/demo/payment/dto/RequestPayDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
이거는 스네이크 케이스로 이름을 바꿔주는건데 이부분은 삭제해야할 것 같습니다 !

2024-07-09 01:41 UTC, soieu commented on src/main/java/com/example/demo/payment/service/PaymentService.java
> +    // IamportResponse<Payment> cancelPayment(String paymentId, CancelPaymentRequest request);
아니용.. ㅎㅎ 지적 감사드립니다 !

2024-07-09 01:45 UTC, soieu commented on src/main/java/com/example/demo/marketpurchaserequest/repository/MarketPurchaseRequestRepository.java
> +    Optional<MarketPurchaseRequest> findRequestAndPaymentAndMember(String id);
JPA 명명 규칙을 공부했습니다... 지적해주신 부분 너무 감사드립니다!

2024-07-09 01:50 UTC, soieu commented on src/main/java/com/example/demo/payment/controller/api/PaymentApiController.java
> +        log.info("결제 응답={}", response.getResponse().toString());
이 로그로 얻을 수 있는 정보가 없네요.. 삭제해야할 것 같습니다 감사합니다!

2024-07-09 01:52 UTC, soieu commented on src/main/java/com/example/demo/payment/dto/RequestPayDto.java
> +@Data
알려주셔서 감사합니다 ! 참고하여 다음 코드짤 때도 유의하겠습니다..!

2024-07-09 01:52 UTC, soieu commented on src/main/java/com/example/demo/payment/dto/RequestPayDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
이부분은 삭제하겠습니다 ! 상은님에게 댓글 달았습니당

2024-07-09 01:53 UTC, soieu commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +                .orElseThrow(() -> new IllegalArgumentException("주문이 없습니다."));
아구 죄송합니다 ㅜ 다 수정한줄알았는데 빠진 부분이 있었네욥..

2024-07-09 01:59 UTC, soieu commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +                marketPurchaseRequestRepository.delete(marketPurchaseRequest);
결제만 삭제하는 방식으로 바꿨습니다 ! 이부분은 제가 잘못생각했네요.. 지적 감사드립니다!

2024-07-09 02:00 UTC, soieu commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +                marketPurchaseRequestRepository.delete(marketPurchaseRequest);
결제만 삭제하는 방식으로 바꿨습니다 ! 이부분은 제가 잘못생각했네요.. 지적 감사드립니다!

2024-07-09 03:40 UTC, hyun-Jin-Park-4808 reviewed
JPA 작성법은 다시 확인해보세요! 쿼리없이 네이밍만으로 조인 가능해요~!

2024-07-09 03:40 UTC, hyun-Jin-Park-4808 commented on gradlew.bat
> +:omega
이 파일은 무엇을 수정한 건가요??

2024-07-09 03:40 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/marketpurchaserequest/repository/MarketPurchaseRequestRepository.java
> +
다시 공부해 보셔야 할 것 같아요 .!

2024-07-09 03:47 UTC, sangeun-b commented on src/main/java/com/example/demo/marketpurchaserequest/repository/MarketPurchaseRequestRepository.java
> +
@soieu 참고하시면 좋을 거 같아서 공식 레퍼런스 공유드려용!
https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html

2024-07-09 05:34 UTC, soieu commented on gradlew.bat
> +:omega
이전과 동일한 내용입니다 ! .gitignore 재적용 하다가 잘못 적용된거같습니당.. 처음부터 끝까지 같은내용이에요!

2024-07-09 05:34 UTC, soieu commented on src/main/java/com/example/demo/marketpurchaserequest/repository/MarketPurchaseRequestRepository.java
> +
수정완료했습니다..!! 공식문서는 두고두고 보겠습니다 감사합니다!

2024-07-09 05:45 UTC, hyun-Jin-Park-4808 approved these changes
고생하셨습니다! 머지할게요 ㅎㅎ

2024-07-09 05:46 UTC, UnaeKang approved these changes
LGTM ddabong🐪

2024-07-09 05:47 UTC, merged