결제 취소 기능 구현
NewDeal-MarkeThing/MarkeThing pull request #25
Opened 2024-07-09 07:29 UTC by soieu

## 코드 변경사항

#### AS-IS

#### TO-BE
- 결제 취소 기능을 추가합니다.

## 테스트 여부
- [x] 테스트 코드
- [x] API 테스트

2024-07-09 09:20 UTC, DongDongShin approved these changes
결제기능 기대하겠습니다~

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 requested changes
고생하셨어요 ㅎㅎ 리뷰 남겼습니다! 수정 부탁드려요~!

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/controller/api/PaymentApiController.java
> +                              @RequestBody CancelPaymentRequest request) {
저희 네이밍 Dto로 통일하면 좋을 것 같아요!

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/dto/CancelPaymentRequest.java
> +
어노테이션 사용해서 생성자 만들어주세요~

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +            com.example.demo.payment.entity.Payment payment = paymentRepository.findById(Long.valueOf(paymentId))
Payment는 import를 시키시는 게 어떨까요?

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/controller/api/PaymentApiController.java
> +    public void cancelPayment(@PathVariable String paymentId,
paymentId Long 타입으로 수정해주세요~

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +            com.example.demo.payment.entity.Payment payment = paymentRepository.findById(Long.valueOf(paymentId))
Long타입으로 바꾸면 여기서 한 번 더 바꿀 필요가 없습니당~

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +            if (!response.getResponse().getStatus().equals("cancelled")) {
보통 equals()함수를 사용할 때는 앞쪽에 null이 터질 가능성이 없는 상수 값을 넣어주고, 뒤쪽에 null이 터질 가능성이 있는 변수 값을 넣어줍니다~!

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/test/java/com/example/demo/payment/controller/api/PaymentApiControllerTest.java
> -        Logger logger = (Logger) LoggerFactory.getLogger(PaymentApiController.class);
logger의 역할은 무엇인가요?

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/test/java/com/example/demo/payment/controller/api/PaymentApiControllerTest.java
> +        // request에 필요한 필드를 설정하세요
이 주석의 의미는 무엇인가요?

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/test/java/com/example/demo/payment/service/PaymentServiceImplTest.java
> +        String paymentId = "1";
paymentId는 Long으로 두시고, 이렇게 paymentId를 지정해줬으면, given에서  any를 사용할 것이 아니라 지정한 값을 사용해야 유의미한 테스트가 될 것 같아요~

2024-07-09 09:30 UTC, hyun-Jin-Park-4808 commented on src/test/java/com/example/demo/payment/service/PaymentServiceImplTest.java
> +        when(paymentRepository.findById(anyLong())).thenReturn(Optional.empty());
여기서 anyLong()을 쓴 부분을 말한 겁니다! any 사용은 최대한 지양해주세요!

2024-07-09 09:33 UTC, soieu commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +            com.example.demo.payment.entity.Payment payment = paymentRepository.findById(Long.valueOf(paymentId))
이름이 동일한 객체가 있어 부득이하게... 요렇게 했습니다

2024-07-09 09:36 UTC, soieu commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +            if (!response.getResponse().getStatus().equals("cancelled")) {
감사합니다 ! 이부분을 헷갈려서 그냥하다가 ㅜ 이렇게 됐네요 지적하신 부분 잊지않겠습니다 ! 감사합니다

2024-07-09 09:37 UTC, soieu commented on src/test/java/com/example/demo/payment/controller/api/PaymentApiControllerTest.java
> -        Logger logger = (Logger) LoggerFactory.getLogger(PaymentApiController.class);
이부분은 삭제한 부분입니당

2024-07-09 09:39 UTC, soieu commented on src/test/java/com/example/demo/payment/controller/api/PaymentApiControllerTest.java
> +        // request에 필요한 필드를 설정하세요
수정했습니다 ! 지적 감사합니당

2024-07-09 09:42 UTC, soieu commented on src/test/java/com/example/demo/payment/service/PaymentServiceImplTest.java
> +        String paymentId = "1";
테스트 코드 작성이 어렵네요 ㅠㅠ any 지양하는것 ! 잊지않도록 하겠습니다 감사합니다!

2024-07-10 04:57 UTC, sangeun-b approved these changes
구현하시느라 고생하셨습니당!!! 멋져요 :) 👍👍👍

2024-07-10 05:14 UTC, soieu commented on src/main/java/com/example/demo/payment/controller/api/PaymentApiController.java
> +                              @RequestBody CancelPaymentRequest request) {
수정했습니당~!

2024-07-10 05:14 UTC, soieu commented on src/main/java/com/example/demo/payment/dto/CancelPaymentRequest.java
> +
넵 !! 적용했습니다

2024-07-10 05:20 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java
> +            com.example.demo.payment.entity.Payment payment = paymentRepository.findById(Long.valueOf(paymentId))
import 경로를 저 경로로 하면 됩니다!

2024-07-10 06:38 UTC, UnaeKang approved these changes
두근두근 결제 좋아요

2024-07-10 06:42 UTC, hyun-Jin-Park-4808 approved these changes
고생하셨습니당!

2024-07-10 06:42 UTC, merged